name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Docker (explicit installation and startup)
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo docker --version

      # Verify Docker is running
      - name: Verify Docker status
        run: sudo systemctl status docker

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t trekwebapp .

      # Run Playwright tests in Docker
      - name: Run Playwright tests in Docker
        run: docker run trekwebapp
